### ISSUE TITLE
"toolsMenu not defined" error thrown when exiting NVDA

### ISSUE THREAD

**Issue by josephsl** [dictationbridge/dictationbridge-nvda#17]
Hi,

When exiting NVDA with DB installed, the following traceback is shown:

ERROR - globalPluginHandler.terminate (08:03:54.124):
Error terminating global plugin <globalPlugins.dictation.GlobalPlugin object at 0x06DBCE50>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 40, in terminate
  File "C:\Users\User\AppData\Roaming\nvda\addons\DictationBridge\globalPlugins\dictation\__init__.py", line 556, in terminate
  File "C:\Users\User\AppData\Roaming\nvda\addons\DictationBridge\globalPlugins\dictation\__init__.py", line 322, in terminate
NameError: global name 'toolsMenu' is not defined
I guess the scope qualifier may not have been used.

Thanks.

**Comment by derekriemer** [comment]
I think that should have said "installmenu" not "toolsMenu"
I fixed this in a commit I'll push up soon, when I do the dictation bridge context sensative help PR.
